
package gui;


public class calculaterInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculaterInterface.class.getName());

   private double num1;
   private double num2;
   private String operator = null;
   
   private double calculate(double n1 , double n2 , String op){
       
   switch (op){
       case "+" : 
           return n1 + n2;
       case "-" :
           return n1- n2;
       case "*" : 
           return n1 * n2;
       case "/" :
           if (n2==0){
               txtField.setText("Error");
               return 0 ;
           }
           return n1/n2;
   }
   return 0;
   }
   
   
   
    public calculaterInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField = new javax.swing.JTextField();
        lblcal = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnmin = new javax.swing.JButton();
        btnmulti = new javax.swing.JButton();
        btndivi = new javax.swing.JButton();
        btnres = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnzero = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtField.setBorder(null);
        getContentPane().add(txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 258, 37));

        lblcal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblcal.setForeground(new java.awt.Color(255, 255, 255));
        lblcal.setText("Calculator");
        getContentPane().add(lblcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(this::btn1ActionPerformed);
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, -1));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(this::btn2ActionPerformed);
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 50, -1));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(this::btn3ActionPerformed);
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, -1));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, -1));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, -1));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 50, -1));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, -1));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(this::btn8ActionPerformed);
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, -1));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, -1));

        btnmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmin.setText("-");
        btnmin.addActionListener(this::btnminActionPerformed);
        getContentPane().add(btnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 50, -1));

        btnmulti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmulti.setText("x");
        btnmulti.addActionListener(this::btnmultiActionPerformed);
        getContentPane().add(btnmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 50, -1));

        btndivi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndivi.setText("/");
        btndivi.addActionListener(this::btndiviActionPerformed);
        getContentPane().add(btndivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 50, 30));

        btnres.setBackground(new java.awt.Color(255, 153, 0));
        btnres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnres.setText("=");
        btnres.addActionListener(this::btnresActionPerformed);
        getContentPane().add(btnres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 43));

        btnplus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnplus.setText("+");
        btnplus.addActionListener(this::btnplusActionPerformed);
        getContentPane().add(btnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 50, -1));

        btnzero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnzero.setText("0");
        btnzero.addActionListener(this::btnzeroActionPerformed);
        getContentPane().add(btnzero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 50, -1));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("C");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/HD-wallpaper-black-background-simple.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
          txtField.setText(txtField.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
         txtField.setText(txtField.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
         txtField.setText(txtField.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
          txtField.setText(txtField.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
          txtField.setText(txtField.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
          txtField.setText(txtField.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
          txtField.setText(txtField.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeroActionPerformed
         txtField.setText(txtField.getText() + "0");
    }//GEN-LAST:event_btnzeroActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
         txtField.setText(txtField.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtField.setText(txtField.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
       
        if(operator!=null){
            double num2 = Double.parseDouble(txtField.getText());
            num1 = calculate(num1, num2, operator);
            txtField.setText(String.valueOf(num1));
        }else{
            num1 = Double.parseDouble(txtField.getText()); 
        }  
        
    operator = "+";
    txtField.setText("");
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
       
        if(operator!=null){
           double num2 = Double.parseDouble(txtField.getText());
           double result = calculate(num1, num2, operator);
           txtField.setText(String.valueOf(result));
                   num1 = result;
                   operator = null;
        }
    }//GEN-LAST:event_btnresActionPerformed

    private void btnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminActionPerformed
            if(operator!=null){
            double num2 = Double.parseDouble(txtField.getText());
            num1 = calculate(num1, num2, operator);
            txtField.setText(String.valueOf(num1));
        }else{
            num1 = Double.parseDouble(txtField.getText()); 
        }    
    operator = "-";
    txtField.setText("");
    }//GEN-LAST:event_btnminActionPerformed

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
           if(operator!=null){
            double num2 = Double.parseDouble(txtField.getText());
            num1 = calculate(num1, num2, operator);
            txtField.setText(String.valueOf(num1));
        }else{
            num1 = Double.parseDouble(txtField.getText()); 
        }  
    operator = "*";
    txtField.setText("");
    }//GEN-LAST:event_btnmultiActionPerformed

    private void btndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiviActionPerformed
            if(operator!=null){
            double num2 = Double.parseDouble(txtField.getText());
            num1 = calculate(num1, num2, operator);
            txtField.setText(String.valueOf(num1));
        }else{
            num1 = Double.parseDouble(txtField.getText()); 
        }  
    operator = "/";
    txtField.setText("");
    }//GEN-LAST:event_btndiviActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    txtField.setText("");
    num1 = 0;
    operator = null;
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculaterInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btndivi;
    private javax.swing.JButton btnmin;
    private javax.swing.JButton btnmulti;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnres;
    private javax.swing.JButton btnzero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcal;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
